export const CLIENT_ID='34ee2285-bee4-49e0-a454-4ff374be4d33'
export const FHIR_BASE_URL='https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4'
export const SMART_AUTH_URL='https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize'
export const SMART_TOKEN_URL='https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token'
export const REDIRECT_URL='http://localhost:8000/api/callback/'
export const CODE_VERIFIER_LOCAL_STORAGE_KEY='smart_code_verifier'
export const TOKEN_RESPONSE_LOCAL_STORAGE_KEY='smart_token_response'